### ISSUE TITLE
1.9 :>

### ISSUE THREAD

**Issue by PhanaticD** [AddstarMC/Prism-Bukkit#11]
are you planning on updating this any more?

**Comment by addstar** [comment]
Yes, definitely. We still use Prism and will continue to maintain it. We haven't done much work on this for a while because it mostly just works fine for us and we haven't needed to.

And yes, we are also working on upgrading our entire network to 1.9, so that will be part of it :smiley: 

We have a lot to work on, as you can imagine, but we will get to this.
Feel free to make any changes and submit PRs.. we are very happy to accept improvements/fixes.
