### ISSUE TITLE
Inspecting twice when right-clicking

### ISSUE THREAD

**Issue by tobire** [AddstarMC/Prism-Bukkit#14]
When a player right clicks to inspect a block, the event is called twice, because of the new Off-Hand features in 1.9.

To fix this just check if PlayerInteractEvent#getHand() == EquipmentSlot.HAND

**Comment by addstar** [comment]
Sorry for the delay in replying.
I must admit I don't think we use the inspection tool, so it probably wasn't noticed. Feel free to submit a PR for us, we're always happy to review code submissions. Otherwise, we'll look into it when we can and try to fix it. But it's low priority for us because we don't use the feature.
