### ISSUE TITLE
[FEATURE] Shulker Support

### ISSUE THREAD

**Issue by Cryptite** [AddstarMC/Prism-Bukkit#286]
Simply put, Prism hasn't since the introduction of Shulkers to Minecraft been able to support rolling back shulker boxes with their respective inventories. 

It tracks inventory events on placed shulkers, but you cannot rollback a shulkerbox break, for example and also get its inventory back.

**Comment by Rothes** [comment]
I only noticed that The `container-access` action is not logged for shulker. Fixed in #274 . Prism will rollback the items in shulker with param `item-remove`, just like what we do with chests.
Do you mean Prism should log the data in shulker when breaking / placing it? But that may cause a mess if we don't add other judgments.

**Comment by Cryptite** [comment]
Correct, it should. You should be able to rollback, for example, an `item-drop` that is a Shulker and it should return the shulker AND its inventory.

**Comment by viveleroi** [comment]
This repository is no longer active. You can try to resubmit this at the current Prism repo here https://github.com/prism/PrismRefracted
