### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by hyrixx** [AddstarMC/Prism-Bukkit#289]
when will you update this plugin for 1.17 / 1.18
please response

**Comment by Rothes** [comment]
https://jenkins.addstar.com.au/job/Prism-Bukkit/lastSuccessfulBuild/
You can download the latest dev build

**Comment by addstar** [comment]
@MEOW2006 We haven't worked on Prism in a while because we've been busy on other things but we do intend to make changes soon. However, the current dev builds (thanks @Rothes for linking it) work fine in 1.17 and our initial testing has also shown no problems in 1.18.

Many plugins do not need a new release just for a new Minecraft update, they can often work just fine without changes.

**Comment by Bobcat00** [comment]
addstar is still alive! :thumbsup:

**Comment by hyrixx** [comment]
> @MEOW2006 We haven't worked on Prism in a while because we've been busy on other things but we do intend to make changes soon. However, the current dev builds (thanks @Rothes for linking it) work fine in 1.17 and our initial testing has also shown no problems in 1.18.
> 
> Many plugins do not need a new release just for a new Minecraft update, they can often work just fine without changes.

thank you so much for your quick response @addstar
