### ISSUE TITLE
Purge Executor seems to not execute....

### ISSUE THREAD

**Issue by Narimm** [AddstarMC/Prism-Bukkit#30]

**Comment by Bobcat00** [comment]
Just found this old issue.  I think the real problem is that ActionParameter#process() is checking permissions without checking if the sender is a player first. This can cause the startup/periodic purge operation to fail, and to make matters worse, it fails silently because error conditions are not logged.

See my commit https://github.com/Bobcat00/Prism-Bukkit/commit/831f4d74c6f8aa0279c04143ad5a072d112905c0 which corrects this and adds additional logging, not just for error conditions, but logging to help with adjusting the timing. (And since it reports each of the purge operations it has processed, you can tell if there was a failure.)
